// src/containers/Product/Add_update/index.tsx
import React, { useState, useEffect } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import {
  reqCategoryList,
  reqAddProduct,
  reqProdById,
  reqUpdateProduct,
} from '../../../api';
import { Card, Form, Input, Button, message, Select } from 'antd';
import { ArrowLeftOutlined } from '@ant-design/icons';
import { PRIMARY, BASE_URL } from '../../../config';
import PictureWall from './PictureWall';
import RichTextEditor from './RichTextEditor';
import { useAppStore } from '../../../store';

// AddUpdate组件
function AddUpdate() {
  const [categoryList, setCategoryList] = useState<
    { value: string; label: string }[]
  >([]);
  const [FormRef] = Form.useForm();
  const editor = React.createRef<any>();
  const picwall = React.createRef<any>();
  const [preimgs, setPreImgs] = useState<string[]>([]);
  const [richtext, setrichtext] = useState('');
  const { pid } = useParams<{ pid: string }>();
  const navigate = useNavigate();

  const productList = useAppStore((s) => s.productList);
  const categoryListFromRedux = useAppStore((s) => s.categoryList);

  // 获取分类列表请求
  async function getCategoryList() {
    const result: any = await reqCategoryList();
    const { code, data, msg } = result;
    if (code === 0) {
      const newData = data.map((item: any) => {
        const obj = { value: item._id, label: item.name };
        return obj;
      });
      setCategoryList(newData);
    } else {
      message.error(msg);
    }
  }

  // 回显数据，统一封装函数
  function fn(data: any, picwall: any, editor: any) {
    const { name, desc, price, categoryid, imgs, detail } = data;
    FormRef.setFieldsValue({
      catename: name,
      desc: desc,
      price: price,
      category: categoryid,
    });
    const arr = imgs.map((item: string) => {
      return {
        uid: Math.random().toString(),
        name: item,
        status: 'done',
        url: BASE_URL + '/api1/upload/' + item,
      };
    });
    picwall.setFileList(arr);
    editor.setHtml(detail);
    setPreImgs(imgs);
    setrichtext(detail);
  }

  // 获取商品信息通过id
  async function getProduct() {
    const editorcurrent = editor.current;
    const picwallcurrent = picwall.current;
    const result: any = await reqProdById(pid!);
    const { code, data } = result;
    if (code === 0) {
      fn(data, picwallcurrent, editorcurrent);
    } else {
      message.error('获取数据失败');
    }
  }

  // 生命周期
  useEffect(() => {
    if (categoryListFromRedux.length) {
      const newData = categoryListFromRedux.map((item: any) => {
        const obj = { value: item._id, label: item.name };
        return obj;
      });
      setCategoryList(newData);
    } else {
      getCategoryList();
    }
    // 如果有id说明进入了修改商品页面
    if (pid) {
      if (productList.length) {
        const result = productList.find((item: any) => {
          return item._id === Number(pid);
        });
        if (result) {
          fn(result, picwall.current, editor.current);
        }
      } else {
        getProduct();
      }
    }
  }, []);

  // 提交表单的回调
  const onFinish = async (values: any) => {
    values.imgs = preimgs;
    values.detail = richtext;
    console.log('Received values of form: ', values);
    let result: any;
    console.log(values);
    if (pid) {
      values.id = pid;
      result = await reqUpdateProduct(values);
    } else {
      result = await reqAddProduct(values);
    }
    const { code } = result;
    if (code === 0) {
      message.success(pid ? '修改商品成功' : '新增商品成功');
      navigate('/admin/prod_about/product');
    } else {
      message.error('新增商品失败');
    }
  };

  return (
    <Card
      title={
        <div className="left_title">
          <Button
            type="link"
            className="left_button"
            onClick={() => {
              navigate(-1);
            }}
            style={{ fontSize: '20px' }}
          >
            <ArrowLeftOutlined style={{ color: PRIMARY }} />
          </Button>
          <span style={{ fontSize: '20px' }}>
            {pid ? '修改商品' : '新增商品'}
          </span>
        </div>
      }
    >
      <Form
        form={FormRef}
        name="addUpdate-form"
        className="addUpdate-form"
        labelCol={{ md: 2 }}
        wrapperCol={{ md: 7 }}
        onFinish={onFinish}
      >
        <Form.Item
          label="商品名称"
          name="catename"
          rules={[
            {
              required: true,
              message: '请输入商品名称',
            },
          ]}
        >
          <Input placeholder="商品名称" />
        </Form.Item>
        <Form.Item
          label="商品描述"
          name="desc"
          rules={[
            {
              required: true,
              message: '请输入商品描述',
            },
          ]}
        >
          <Input placeholder="商品描述" />
        </Form.Item>
        <Form.Item
          label="商品价格"
          name="price"
          rules={[
            {
              required: true,
              message: '请输入商品价格',
            },
          ]}
        >
          <Input prefix="￥" suffix="元" type="number" placeholder="商品价格" />
        </Form.Item>
        <Form.Item
          label="商品分类"
          name="category"
          rules={[
            {
              required: true,
              message: '请输入商品分类',
            },
          ]}
        >
          <Select options={categoryList} placeholder="请选择分类" />
        </Form.Item>
        <Form.Item label="商品图片" wrapperCol={{ md: 17 }}>
          <PictureWall
            ref={picwall}
            preimgs={preimgs}
            setPreImgs={setPreImgs}
          />
        </Form.Item>
        <Form.Item label="商品详情" name="detail" wrapperCol={{ md: 17 }}>
          <RichTextEditor ref={editor} setrichtext={setrichtext} />
        </Form.Item>
        <Form.Item
          wrapperCol={{
            offset: 8,
            span: 16,
          }}
        >
          <Button type="primary" htmlType="submit">
            Submit
          </Button>
        </Form.Item>
      </Form>
    </Card>
  );
}

export default AddUpdate;

// src/views/product/add-update.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { ArrowLeftOutlined } from '@ant-design/icons-vue';
import { message } from 'ant-design-vue';
import type { FormInstance } from 'ant-design-vue';
import { PRIMARY } from '@/config';
import { reqCategoryList, reqAddProduct, reqProdById, reqUpdateProduct } from '@/api';
import { useAppStore } from '@/stores/app';
import PictureWall from '@/components/PictureWall.vue';
import RichTextEditor from '@/components/RichTextEditor.vue';

const route = useRoute();
const router = useRouter();
const appStore = useAppStore();

const pid = (route.params.pid as string) || '';
const isEdit = !!pid;

const categoryList = ref<{ value: string; label: string }[]>([]);
const formRef = ref<any>();
const preImgs = ref<string[]>([]);
const richText = ref('');
const picWallRef = ref<any>(null);

async function getCategoryList() {
  const result: any = await reqCategoryList();
  const { code, data, msg } = result;
  if (code === 0) {
    categoryList.value = data.map((item: any) => ({
      value: item._id,
      label: item.name,
    }));
  } else {
    message.error(msg);
  }
}

function fillForm(data: any) {
  formRef.value?.setFieldsValue({
    catename: data.name,
    desc: data.desc,
    price: data.price,
    category: data.categoryid,
  });
  const arr = (data.imgs || []).map((item: string) => ({
    uid: Math.random().toString(),
    name: item,
    status: 'done',
    url: `/api1/upload/${item}`,
  }));
  picWallRef.value?.setFileList(arr);
  richText.value = data.detail || '';
  preImgs.value = data.imgs || [];
}

async function getProduct() {
  const result: any = await reqProdById(pid);
  const { code, data } = result;
  if (code === 0) {
    fillForm(data);
  } else {
    message.error('获取数据失败');
  }
}

onMounted(() => {
  if (appStore.categoryList.length) {
    categoryList.value = appStore.categoryList.map((item: any) => ({
      value: item._id,
      label: item.name,
    }));
  } else {
    getCategoryList();
  }

  if (pid) {
    if (appStore.productList.length) {
      const info = appStore.productList.find((item: any) => String(item._id) === pid);
      if (info) {
        fillForm(info);
        return;
      }
    }
    getProduct();
  }
});

async function onFinish(values: any) {
  values.imgs = preImgs.value;
  values.detail = richText.value;
  console.log('Submitted:', values);

  let result: any;
  if (pid) {
    values.id = pid;
    result = await reqUpdateProduct(values);
  } else {
    result = await reqAddProduct(values);
  }

  if (result.code === 0) {
    message.success(pid ? '修改商品成功' : '新增商品成功');
    router.push('/admin/prod_about/product');
  } else {
    message.error('操作失败');
  }
}
</script>

<template>
  <a-card>
    <template #title>
      <div style="display: flex; align-items: center;">
        <a-button type="link" @click="router.back()" style="font-size: 20px;">
          <ArrowLeftOutlined :style="{ color: PRIMARY }" />
        </a-button>
        <span style="font-size: 20px;">{{ isEdit ? '修改商品' : '新增商品' }}</span>
      </div>
    </template>

    <a-form
      ref="formRef"
      name="addUpdate-form"
      :label-col="{ md: 2 }"
      :wrapper-col="{ md: 7 }"
      @finish="onFinish"
    >
      <a-form-item
        label="商品名称"
        name="catename"
        :rules="[{ required: true, message: '请输入商品名称' }]"
      >
        <a-input placeholder="商品名称" />
      </a-form-item>

      <a-form-item
        label="商品描述"
        name="desc"
        :rules="[{ required: true, message: '请输入商品描述' }]"
      >
        <a-input placeholder="商品描述" />
      </a-form-item>

      <a-form-item
        label="商品价格"
        name="price"
        :rules="[{ required: true, message: '请输入商品价格' }]"
      >
        <a-input prefix="￥" suffix="元" type="number" placeholder="商品价格" />
      </a-form-item>

      <a-form-item
        label="商品分类"
        name="category"
        :rules="[{ required: true, message: '请选择商品分类' }]"
      >
        <a-select :options="categoryList" placeholder="请选择分类" />
      </a-form-item>

      <a-form-item label="商品图片" :wrapper-col="{ md: 17 }">
        <PictureWall ref="picWallRef" :preimgs="preImgs" :set-pre-imgs="(v: string[]) => preImgs = v" />
      </a-form-item>

      <a-form-item label="商品详情" :wrapper-col="{ md: 17 }">
        <RichTextEditor v-model:richtext="richText" />
      </a-form-item>

      <a-form-item :wrapper-col="{ offset: 8, span: 16 }">
        <a-button type="primary" html-type="submit">Submit</a-button>
      </a-form-item>
    </a-form>
  </a-card>
</template>
