// src/containers/Admin/Sidebar/index.tsx
import { useLocation, useNavigate } from 'react-router-dom';
import { useAppStore } from '../../../store';

// 引入菜单配置
import menu from '../../../config/menu_config';
import type { MenuItemConfig } from '../../../config/menu_config';
import { Menu } from 'antd';
import logo from '../../../static/imgs/wer.png';
import './index.scss';

// 组件
function Sidebar() {
  const location = useLocation();
  const navigate = useNavigate();
  const user = useAppStore((s) => s.userInfo.user);
  const saveTitle = useAppStore((s) => s.saveTitle);

  // 是否具有菜单权限
  function hasAuth(item: MenuItemConfig) {
    const username = user?.username;
    const role = user?.role;
    if (username === 'admin' && role) {
      return true;
    } else if (!item.children && role) {
      return role.includes(item.key);
    } else if (item.children && role) {
      return item.children.find((item2) => {
        return role.includes(item2.key);
      });
    }
  }

  // 定义创建菜单的递归函数
  function createMenu(menuarr: MenuItemConfig[] | undefined) {
    if (menuarr) {
      const arr = menuarr.map((item) => {
        if (hasAuth(item)) {
          return {
            key: item.key,
            icon: item.icon,
            children: createMenu(item.children),
            label: item.title,
          };
        }
      });
      return arr.filter((item) => {
        return item;
      });
    }
  }

  // 定义items
  const items = createMenu(menu);

  // 选中标签跳转至对应路径
  function selectItem(info: any) {
    const { key, keyPath, domEvent } = info;
    // 保存title至store
    saveTitle((domEvent.target as HTMLElement).innerHTML);
    if (keyPath[1]) {
      navigate(keyPath[1] + '/' + keyPath[0]);
    } else {
      navigate(key);
    }
  }

  // selectedKeys的值，根据地址决定侧边栏标签高亮
  function fn() {
    if (location.pathname.includes('product')) {
      return 'product';
    }
    return location.pathname.split('/').reverse()[0];
  }

  return (
    <div className="sidebar">
      <header className="nav_header">
        <img src={logo} alt="" />
        <h1>商品管理系统</h1>
      </header>
      <Menu
        selectedKeys={[fn()]}
        defaultOpenKeys={location.pathname.split('/').splice(2)}
        mode="inline"
        theme="dark"
        items={items}
        onSelect={selectItem}
      />
    </div>
  );
}

export default Sidebar;

// src/components/Sidebar.vue
<script setup lang="ts">
import { h, computed } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { useAuthStore } from '@/stores/auth';
import { useAppStore } from '@/stores/app';
import menuConfig from '@/config/menu';
import type { MenuItemConfig } from '@/config/menu';

const route = useRoute();
const router = useRouter();
const authStore = useAuthStore();
const appStore = useAppStore();

function hasAuth(item: MenuItemConfig): boolean {
  const username = authStore.user?.username;
  const role = authStore.user?.role;
  if (username === 'admin' && role) return true;
  if (!item.children && role) return role.includes(item.key);
  if (item.children && role) {
    return !!item.children.find((child) => role.includes(child.key));
  }
  return false;
}

function buildMenu(menuArr: MenuItemConfig[] | undefined): any[] {
  if (!menuArr) return [];
  return menuArr
    .filter(hasAuth)
    .map((item) => ({
      key: item.key,
      icon: item.icon ? () => h(item.icon) : undefined,
      label: item.title,
      children: item.children ? buildMenu(item.children) : undefined,
    }));
}

// 响应式菜单项 — 随 authStore.user 变化自动更新
const items = computed(() => buildMenu(menuConfig));

// 响应式高亮
const selectedKeys = computed(() => {
  const path = route.path;
  if (path.includes('product')) return ['product'];
  return [path.split('/').reverse()[0]];
});

// 展开的菜单组
const openKeys = computed(() => {
  const parts = route.path.split('/');
  // 获取 /admin/prod_about/product 中的 ['prod_about']
  // 两级路径如 /admin/prod_about/product → 展开 prod_about
  // 三级路径如 /admin/charts/bar → 展开 charts
  if (parts.length >= 3) return [parts[2]];
  return [];
});

function selectItem(info: { key: string; keyPath: string[]; domEvent: MouseEvent }) {
  const { key } = info;
  appStore.setTitle((info.domEvent.target as HTMLElement)?.innerText || '');
  // 菜单 key 与路由 name 一致，直接用命名路由跳转
  router.push({ name: key });
}
</script>

<template>
  <div class="sidebar">
    <header class="nav_header">
      <img src="/wer.png" alt="logo" />
      <h1>商品管理系统</h1>
    </header>
    <a-menu
      :selected-keys="selectedKeys"
      :open-keys="openKeys"
      mode="inline"
      theme="dark"
      :items="items"
      @select="selectItem"
    />
  </div>
</template>

<style scoped lang="scss">
.sidebar {
  .nav_header {
    display: flex;
    align-items: center;
    padding: 16px;
    img {
      width: 40px;
      height: 40px;
      margin-right: 10px;
    }
    h1 {
      color: #fff;
      font-size: 18px;
      white-space: nowrap;
      margin: 0;
    }
  }
}
</style>
