// src/containers/Bar/index.jsx
import {useEffect, useRef} from 'react'

export default function Bar() {
  const wsRef = useRef(null);

  useEffect(() => {
    const ws = new WebSocket('http://localhost:3001');
    wsRef.current = ws;

    ws.onopen = () => {
      console.log('WebSocket 已连接');
    };

    ws.onmessage = (event) => {
      try {
        const data = JSON.parse(event.data);
        onMessage && onMessage(data);
      } catch (e) {
        console.log('收到非 JSON 消息:', event.data);
      }
    };

    ws.onclose = (event) => {
      console.log('WebSocket 已关闭', event.code);
    };

    ws.onerror = (error) => {
      console.error('WebSocket 错误:', error);
    };

    // 清理函数：卸载时关闭连接
    return () => {
      ws.close(1000, '组件卸载');
    };
  }, []); // 仅 url 变化时重连

  return (
    <div>Bar</div>
  )
}

// src/views/charts/bar.vue
<script setup lang="ts">
import { onMounted, onUnmounted, ref } from 'vue';

let ws: WebSocket | null = null;

onMounted(() => {
  ws = new WebSocket('ws://localhost:3001');
  ws.onopen = () => console.log('WebSocket 已连接');
  ws.onmessage = (event) => {
    try {
      const data = JSON.parse(event.data);
      console.log('收到消息:', data);
    } catch {
      console.log('收到非 JSON 消息:', event.data);
    }
  };
  ws.onclose = (event) => console.log('WebSocket 已关闭', event.code);
  ws.onerror = (error) => console.error('WebSocket 错误:', error);
});

onUnmounted(() => {
  ws?.close(1000, '组件卸载');
});
</script>

<template>
  <div>Bar</div>
</template>
